- name: "blocked"
  color: "b60205"
  
- name: "bug"
  color: "ba303e"

- name: "can't reproduce"
  color: "8945f2"

- name: "docs"
  color: "7968d9"

- name: "duplicate"
  color: "6884f5"

- name: "enhancement"
  color: "be00ad"

- name: "feature request"
  color: "79e599"

- name: "needs info"
  color: "fad54e"

- name: "priority 🔴"
  color: "b60205"

- name: "priority 🟠"
  color: "d93f0b"

- name: "priority 🟡"
  color: "fbca04"

- name: "reproducible"
  color: "34eb9b"