name: Label sync

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels.yml'
  pull_request:
    paths:
      - '.github/labels.yml'

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Label sync
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.LABEL_SYNC }}
          yaml-file: .github/labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
          exclude: |
            help*
            *issue